name = "ReformulationKit"
uuid = "ccf8701a-f1e2-43fb-9872-b69ec7886d0a"
authors = ["Guillaume Marques <guillaume@nablarise.com>"]
version = "0.1.0"

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"

[extras]
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
MatheuristicKit = "80cb12ff-82f2-4480-ba96-d7ea4e9f45d8"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "GLPK", "MatheuristicKit", "Revise"]

[sources]
MatheuristicKit = {path = "../../dev/MatheuristicKit"}